@startuml use-case-1
left to right direction
skinparam packageStyle rectangle
skinparam monochrome true
actor پرستار as nurse
actor پزشک as doctor
actor کاربر as user
rectangle سیب {
  nurse -- (checkout)
  (checkout) .> (payment) : include
  (checkout) -- clerk
  customer -- (help)
}
@enduml